application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"
email_client:
  base_url: "https://api.sendgrid.com"
  sender_email: "orukele.dev@gmail.com"
  authorization_token: "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"
