application:
  port: 8000
  host: 0.0.0.0
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "newsletter"
email_client:
  base_url: "https://api.sendgrid.com/v3/mail"
  sender_email: "orukele.dev@gmail.com"
  authorization_token: "Secret-Token-Here"
  timeout_milliseconds: 1000
